=== PatchalaMahitha/Wipro_TNP/Wipro_TNP/src/XML/DTD/products.dtd
<!ELEMENT products (product+)>
<!ELEMENT product (code, price, colors)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT colors (color+)>
<!ELEMENT color (#PCDATA)>

=== PatchalaMahitha/Wipro_TNP/Wipro_TNP/src/XML/DTD/products.xml
<?xml version="1.0"?>
<!DOCTYPE products SYSTEM "products.dtd">

<products>
    <product>
        <code>QWZ5671</code>
        <price>39.95</price>
        <colors>
            <color>Red</color>
            <color>Burgundy</color>
        </colors>
    </product>

    <product>
        <code>RRX9856</code>
        <price>42.50</price>
        <colors>
            <color>Red</color>
            <color>Navy</color>
            <color>Burgundy</color>
            <color>Black</color>
        </colors>
    </product>
</products>
